// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDAh24LbEuy3r12EGEB8PaVksHcEmWW4',
    appId: '1:992134643763:web:86e657866ec578e1d66346',
    messagingSenderId: '992134643763',
    projectId: 'watch-store-52e86',
    authDomain: 'watch-store-52e86.firebaseapp.com',
    storageBucket: 'watch-store-52e86.firebasestorage.app',
    measurementId: 'G-166V45LJ4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRKp3th9PlRR7A11IAQr6EMafbyxxQgDo',
    appId: '1:992134643763:android:0a55278991171301d66346',
    messagingSenderId: '992134643763',
    projectId: 'watch-store-52e86',
    storageBucket: 'watch-store-52e86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASeyO5ZYssnI_1ufowGAnTBgYorw1Mits',
    appId: '1:992134643763:ios:b7114155f6e017bbd66346',
    messagingSenderId: '992134643763',
    projectId: 'watch-store-52e86',
    storageBucket: 'watch-store-52e86.firebasestorage.app',
    iosBundleId: 'com.example.diStateManagment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASeyO5ZYssnI_1ufowGAnTBgYorw1Mits',
    appId: '1:992134643763:ios:b7114155f6e017bbd66346',
    messagingSenderId: '992134643763',
    projectId: 'watch-store-52e86',
    storageBucket: 'watch-store-52e86.firebasestorage.app',
    iosBundleId: 'com.example.diStateManagment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGDAh24LbEuy3r12EGEB8PaVksHcEmWW4',
    appId: '1:992134643763:web:d40d1747ff17047dd66346',
    messagingSenderId: '992134643763',
    projectId: 'watch-store-52e86',
    authDomain: 'watch-store-52e86.firebaseapp.com',
    storageBucket: 'watch-store-52e86.firebasestorage.app',
    measurementId: 'G-RSY1TMHKZV',
  );
}
